## Opay Bank Statement Parser

In [4]:
import pymupdf
import pandas as pd
import re

## Extracting and Loading Data

In [5]:
tables = []
with pymupdf.open('opay_bankstatement.pdf') as doc:
    print(len(doc))
    for page_number in range(len(doc)):
        page = doc.load_page(page_number)
        text_blocks = page.get_text('blocks')

        sorted_blocks = sorted(text_blocks, key=lambda b: b[1])

        table_data = []
        for block in sorted_blocks:
            # print(block)
            lines = block[4].split('\n')
            # print(lines)
            table_data.append(lines)

        if table_data:
            df = pd.DataFrame(table_data)
            processed_df = df
            # print(processed_df)

            if not processed_df.empty:
                # print(processed_df)
                tables.append(processed_df)

    if tables:
        concatenated_df = pd.concat(tables, ignore_index=True)
        bank_statement = concatenated_df
    else:
        bank_statement = pd.DataFrame()

33

In [6]:
# Renaming Columns
col = ['Trans.Time', 'Value Date', 'Description', 'Debit/Credit(#)', 'Balance(#)', 'Channel', 'Transaction Reference',
'NoneDrop']
bank_statement.columns = col

In [7]:
# Dropping multiple headers and rows with irrelevant values.
bs_df = bank_statement.copy()
bs_df = bs_df.drop(bs_df[bs_df['Trans.Time']=='Trans. Time'].index)
bs_df = bs_df[~bs_df['Trans.Time'].str.contains('^[A-Z]', regex=True)]
bs_df = bs_df[~bs_df['Trans.Time'].str.contains('^₦', regex=True)]

In [ ]:
date_pattern = re.compile(r"\d{2} [A-Za-z]{3} \d{4}$")
dt_complete_mapper = re.compile(r'^\d{4}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{2}\s\d{2}:\d{2}:\d{2}$')
# dt_incomplete_mapper = re.compile(r'^\d{4}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{2}\s\d{2}:\d{2}:$')

bs_df = bs_df.copy()
def check_datetime(row):
    cell_1 = str(row[0])
    return bool(
        re.match(date_pattern, cell_1)
        or
        re.match(dt_complete_mapper, cell_1))
        # or 
        # re.match(dt_incomplete_mapper, cell_1))

bs_df = bs_df[bs_df.apply(check_datetime, axis=1)]
bs_df.to_csv('open_second.csv')

#### Tasks
- Shift rows with cell in column(Trans.Time) that matches [dd Month Year] format to the right.
- Delete Trans.Time column.
- Drop None values

#### Separating columns dataframe based on shifting goal

In [9]:
nas_dropped = bs_df.dropna(subset=['Balance(#)']).reset_index()
df_to_shift = nas_dropped[~(nas_dropped['Channel'] == 'E-Channel')].reset_index()
df_stable = nas_dropped[nas_dropped['Channel'] == 'E-Channel'].reset_index()

df_stable.info()
df_to_shift.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   level_0                202 non-null    int64
 1   index                  202 non-null    int64
 2   Trans.Time             202 non-null    object
 3   Value Date             202 non-null    object
 4   Description            202 non-null    object
 5   Debit/Credit(#)        202 non-null    object
 6   Balance(#)             202 non-null    object
 7   Channel                202 non-null    object
 8   Transaction Reference  202 non-null    object
 9   NoneDrop               201 non-null    object
dtypes: int64(2), object(8)
memory usage: 15.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   level_0                542 non-null    int64
 1   index                  542 non-null    int64
 2   Trans.Time             542 non-null    object
 3   Value Date             542 non-null    object
 4   Description            542 non-null    object
 5   Debit/Credit(#)        542 non-null    object
 6   Balance(#)             542 non-null    object
 7   Channel                542 non-null    object
 8   Transaction Reference  538 non-null    object
 9   NoneDrop               0 non-null      object
dtypes: int64(2), object(8)
memory usage: 42.5+ KB

### Performing shifting on dataframe selected.

In [10]:
shift_criteria = df_to_shift['Trans.Time'].str.contains('r"\b\d{2} [A-Za-z]{3} \d{4}\b"', regex=True).notna()
shift_criteria.index

for index in shift_criteria.index:
    index = int(index)
    df_to_shift.iloc[index,:] = df_to_shift.iloc[index,:].shift()
df_to_shift = df_to_shift

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_31068\2062310880.py:1: SyntaxWarning: invalid escape sequence '\d'
  shift_criteria = df_to_shift['Trans.Time'].str.contains('r"\b\d{2} [A-Za-z]{3} \d{4}\b"', regex=True).notna()

### Joining Both Transformed Dataframe together

In [83]:
final_df = pd.concat([df_stable,df_to_shift], axis=0)
final_df = final_df.drop(columns=['level_0', 'index', 'Trans.Time', 'NoneDrop']).reset_index()
final_df = final_df.drop(columns='index')
final_df

,Value Date,Description,Debit/Credit(#),Balance(#),Channel,Transaction Reference
0,12 Mar 2024,Spend & Save Withdrawal,"+2,394.69","2,394.69",E-Channel,240312014770779834
1,12 Mar 2024,OWealth Deposit(AutoSave),-294.69,0.00,E-Channel,240312145795962609
2,27 Mar 2024,Transfer from NWAGBO CHINEDUM OBIOMA,"+4,500.00","4,500.00",E-Channel,000004240327184135633860074199
3,12 Apr 2024,Transfer from EBENEZER AYOMIKUN FALODUN,"+10,000.00","10,000.00",E-Channel,000014240412184328237230179735
4,12 Apr 2024,OWealth Deposit(AutoSave),"-10,000.00",0.00,E-Channel,240412146767712953
...,...,...,...,...,...,...
739,30 Mar 2025,OWealth Interest Earned,+0.09,0.71,E-Channel,2503309971yubCWGb81ei38grs5BvL
740,31 Mar 2025,OWealth Interest Earned,+0.09,0.80,E-Channel,250331991NjIlD3hc3FB1cfDlCnNp1
741,01 Apr 2025,OWealth Interest Earned,+0.09,0.89,E-Channel,250401993FeW6pQKUwq8gwbX6pXZ39
742,02 Apr 2025,OWealth Interest Earned,+0.09,0.98,E-Channel,250402995dD0FEHSCceB5u4PBUOpUQ
743,03 Apr 2025,OWealth Interest Earned,+0.09,1.07,E-Channel,250403997CmOUgwCGrTrJUmAflRcoi

In [57]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Value Date             744 non-null    object
 1   Description            744 non-null    object
 2   Debit/Credit(#)        744 non-null    object
 3   Balance(#)             744 non-null    object
 4   Channel                744 non-null    object
 5   Transaction Reference  744 non-null    object
dtypes: object(6)
memory usage: 35.0+ KB

### Assigning Correct Datatypes

In [84]:
final_df['Value Date'] = pd.to_datetime(final_df['Value Date'])
final_df['Balance(#)'] = final_df['Balance(#)'].replace(r',', '', regex=True)
final_df['Balance(#)'] = final_df['Balance(#)'].replace(r'--', '0', regex=True).astype(float)
final_df['Debit/Credit(#)'] = final_df['Debit/Credit(#)'].replace(r',', '', regex=True).astype(float)

final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Value Date             744 non-null    datetime64[ns]
 1   Description            744 non-null    object
 2   Debit/Credit(#)        744 non-null    float64
 3   Balance(#)             744 non-null    float64
 4   Channel                744 non-null    object
 5   Transaction Reference  744 non-null    object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 35.0+ KB

### Creating new credit and debit columns

In [86]:
final_df['Credit'] = round(final_df['Debit/Credit(#)'].apply(lambda x:x if x > 0 else 0), 2)
final_df['Debit'] = abs(round(final_df['Debit/Credit(#)'].apply(lambda x:x if x < 0 else 0), 2))
final_df.head(4)

,Value Date,Description,Debit/Credit(#),Balance(#),Channel,Transaction Reference,Credit,Debit
0,2024-03-12,Spend & Save Withdrawal,2394.69,2394.69,E-Channel,240312014770779834,2394.69,0.00
1,2024-03-12,OWealth Deposit(AutoSave),-294.69,0.00,E-Channel,240312145795962609,0.00,294.69
2,2024-03-27,Transfer from NWAGBO CHINEDUM OBIOMA,4500.00,4500.00,E-Channel,000004240327184135633860074199,4500.00,0.00
3,2024-04-12,Transfer from EBENEZER AYOMIKUN FALODUN,10000.00,10000.00,E-Channel,000014240412184328237230179735,10000.00,0.00

In [88]:
# Drop Debit/Credit Column
opay_clean = final_df.drop('Debit/Credit(#)', axis=1)

### Transform cleaned data to specified format.

In [95]:
def transform_row_alat(row):
    return {
        "type": "debit" if int(row["Debit"]) > 0 else "credit",
        "amount": row["Debit"] if int(row["Debit"]) > 0 else row["Credit"],
        "narration": row["Description"].replace(r"'", ""),
        "date": row["Value Date"],
        "balance": row["Balance(#)"] 
    }
transformed_opay = opay_clean.apply(transform_row_alat, axis=1).tolist()
transformed_opay_df = pd.DataFrame(transformed_opay)
transformed_opay_df.head(5)
transformed_opay_df.to_csv('Transformed_bs.csv')

### Convert to json

In [92]:
transformed_opay_df.to_json(orient='records')

'[{"type":"credit","amount":2394.69,"narration":"Spend & Save Withdrawal","date":1710201600000,"balance":2394.69},{"type":"debit","amount":294.69,"narration":"OWealth Deposit(AutoSave)","date":1710201600000,"balance":0.0},{"type":"credit","amount":4500.0,"narration":"Transfer from NWAGBO CHINEDUM OBIOMA","date":1711497600000,"balance":4500.0},{"type":"credit","amount":10000.0,"narration":"Transfer from EBENEZER AYOMIKUN FALODUN","date":1712880000000,"balance":10000.0},{"type":"debit","amount":10000.0,"narration":"OWealth Deposit(AutoSave)","date":1712880000000,"balance":0.0},{"type":"credit","amount":45000.0,"narration":"Transfer from AROWOSEGBE VICTOR IYANUOLUWA","date":1712966400000,"balance":45000.0},{"type":"debit","amount":45000.0,"narration":"OWealth Deposit(AutoSave)","date":1712966400000,"balance":0.0},{"type":"credit","amount":2225.44,"narration":"Spend & Save Withdrawal","date":1713398400000,"balance":2225.44},{"type":"debit","amount":800.0,"narration":"Transfer to R A Paradise 2","date":1713398400000,"balance":1425.44},{"type":"credit","amount":521.29,"narration":"OWealth Withdrawal","date":1713398400000,"balance":1906.73},{"type":"debit","amount":1600.0,"narration":"Transfer to ALIMOT SADIAT KAREEM","date":1713398400000,"balance":306.73},{"type":"debit","amount":306.73,"narration":"OWealth Deposit(AutoSave)","date":1713398400000,"balance":0.0},{"type":"debit","amount":10000.0,"narration":"OWealth Deposit(AutoSave)","date":1715126400000,"balance":0.0},{"type":"debit","amount":15500.0,"narration":"Transfer to OLUWASEUN CHRISTIANAH AKINTADE","date":1729209600000,"balance":84500.0},{"type":"debit","amount":40000.0,"narration":"Transfer to Victor Arowosegbe FLW","date":1729209600000,"balance":43725.0},{"type":"debit","amount":2000.0,"narration":"Spend & Save Deposit","date":1729209600000,"balance":41725.0},{"type":"debit","amount":5.0,"narration":"Spend & Save Deposit","date":1729209600000,"balance":41720.0},{"type":"debit","amount":5.0,"narration":"Spend & Save Deposit","date":1729209600000,"balance":41715.0},{"type":"debit","amount":15400.0,"narration":"Transfer to LARRYKAY COMMUNICATION5","date":1729209600000,"balance":26315.0},{"type":"debit","amount":770.0,"narration":"Spend & Save Deposit","date":1729209600000,"balance":25545.0},{"type":"debit","amount":10000.0,"narration":"Transfer to OLUGBOYEGA AYODEJI DANIELS","date":1729209600000,"balance":15545.0},{"type":"debit","amount":500.0,"narration":"Spend & Save Deposit","date":1729209600000,"balance":15045.0},{"type":"debit","amount":15045.0,"narration":"OWealth Deposit","date":1729209600000,"balance":0.0},{"type":"credit","amount":1000.0,"narration":"Transfer from KIKELOMO STELLA MODUPE","date":1729987200000,"balance":5000.0},{"type":"debit","amount":25.0,"narration":"Spend & Save Deposit","date":1730073600000,"balance":4622.0},{"type":"credit","amount":22000.0,"narration":"Transfer from Lemonade Technology Limited","date":1730332800000,"balance":22000.0},{"type":"debit","amount":3100.0,"narration":"Transfer to RASHEED ABIMBOLA YAHYAH","date":1730332800000,"balance":18900.0},{"type":"debit","amount":155.0,"narration":"Spend & Save Deposit","date":1730332800000,"balance":18745.0},{"type":"debit","amount":3450.0,"narration":"Transfer to OLABIMPE ANIMASAHUN","date":1730332800000,"balance":15295.0},{"type":"debit","amount":172.5,"narration":"Spend & Save Deposit","date":1730332800000,"balance":15122.5},{"type":"debit","amount":500.0,"narration":"Spend & Save Deposit","date":1730332800000,"balance":4622.5},{"type":"debit","amount":4622.5,"narration":"OWealth Deposit(AutoSave)","date":1730332800000,"balance":0.0},{"type":"credit","amount":10000.0,"narration":"Transfer from SUNKANMI AUGUSTINE AKINBOLADE","date":1730505600000,"balance":10000.0},{"type":"credit","amount":10000.0,"narration":"Transfer from AROWOSEGBE ALICE MORADEKE","date":1731801600000,"balance":10000.0},{"type":"credit","amount":19550.0,"narration":"Transfer from AROWOSEGBE VICTOR IYANUOLUWA","date":1732233600000,"balance":69550.0},{"type":"debit","amount":10300.0,"narration":"Transfer to YEMISI PRECIOUS OYENYEN","date":1732233600000,"balance":59250.0},{"type":"debit","amount":28500.0,"narration":"OPay Card Payment","date":1732233600000,"balance":30235.0},{"type":"debit","amount":3000.0,"narration":"Transfer to AROWOSEGBE ALICE MORADEKE","date":1732233600000,"balance":21985.0},{"type":"debit","amount":150.0,"narration":"Spend & Save Deposit","date":1732233600000,"balance":21835.0},{"type":"debit","amount":21835.0,"narration":"OWealth Deposit(AutoSave)","date":1732233600000,"balance":0.0},{"type":"debit","amount":770.0,"narration":"Spend & Save Deposit","date":1732665600000,"balance":3700.0},{"type":"debit","amount":15400.0,"narration":"Transfer to ALH ABU ABK HAMDALA 1","date":1732665600000,"balance":3700.0},{"type":"debit","amount":2930.0,"narration":"OWealth Deposit(AutoSave)","date":1732665600000,"balance":0.0},{"type":"debit","amount":4000.0,"narration":"OWealth Deposit(AutoSave)","date":1733097600000,"balance":0.0},{"type":"debit","amount":2100.0,"narration":"Transfer to SIGO CLASSES","date":1733356800000,"balance":44590.0},{"type":"debit","amount":105.0,"narration":"Spend & Save Deposit","date":1733356800000,"balance":44485.0},{"type":"debit","amount":44485.0,"narration":"OWealth Deposit(AutoSave)","date":1733356800000,"balance":0.0},{"type":"credit","amount":1000.0,"narration":"Transfer from OLUWABUSOLA HAPPINESS OSIBOYEJO","date":1733616000000,"balance":2000.0},{"type":"credit","amount":70000.0,"narration":"Transfer from AROWOSEGBE VICTOR IYANUOLUWA","date":1733875200000,"balance":70000.0},{"type":"debit","amount":50.0,"narration":"Electronic Money Transfer Levy","date":1733875200000,"balance":69950.0},{"type":"debit","amount":7030.0,"narration":"Transfer to Victor Arowosegbe FLW","date":1733875200000,"balance":62920.0},{"type":"debit","amount":351.5,"narration":"Spend & Save Deposit","date":1733875200000,"balance":62568.5},{"type":"debit","amount":20000.0,"narration":"Transfer to AROWOSEGBE ALICE MORADEKE","date":1733875200000,"balance":42568.5},{"type":"debit","amount":1000.0,"narration":"Spend & Save Deposit","date":1733875200000,"balance":41568.5},{"type":"debit","amount":10000.0,"narration":"Transfer to HM-Victor Arowosegbe FLW","date":1733875200000,"balance":31568.5},{"type":"debit","amount":500.0,"narration":"Spend & Save Deposit","date":1733875200000,"balance":31068.5},{"type":"debit","amount":31068.5,"narration":"OWealth Deposit(AutoSave)","date":1733875200000,"balance":0.0},{"type":"credit","amount":15000.0,"narration":"Transfer from OLUWATOBI BIDEMI AJOBIEWE","date":1734307200000,"balance":40950.0},{"type":"debit","amount":50.0,"narration":"Electronic Money Transfer Levy","date":1734307200000,"balance":40900.0},{"type":"debit","amount":40900.0,"narration":"Transfer to KAZEEM GBADEGESIN AJIBOLA","date":1734307200000,"balance":0.0},{"type":"credit","amount":4000.0,"narration":"Transfer from OLADELE ISAAC SUNDAY","date":1734307200000,"balance":4000.0},{"type":"debit","amount":25.0,"narration":"Spend & Save Deposit","date":1734307200000,"balance":3975.0},{"type":"debit","amount":3975.0,"narration":"OWealth Deposit(AutoSave)","date":1734307200000,"balance":0.0},{"type":"debit","amount":50.0,"narration":"Electronic Money Transfer Levy","date":1734739200000,"balance":98950.0},{"type":"credit","amount":900.0,"narration":"Transfer from AROWOSEGBE VICTOR IYANUOLUWA","date":1734739200000,"balance":900.0},{"type":"debit","amount":25.0,"narration":"Spend & Save Deposit","date":1736985600000,"balance":11425.0},{"type":"debit","amount":925.0,"narration":"OWealth Deposit(AutoSave)","date":1736985600000,"balance":0.0},{"type":"debit","amount":1079.0,"narration":"OWealth Deposit(AutoSave)","date":1737158400000,"balance":0.0},{"type":"debit","amount":10000.0,"narration":"Transfer to POS Transfer-WISDOM CHUKWUDI IGWEZE","date":1740268800000,"balance":0.0},{"type":"credit","amount":10000.0,"narration":"Transfer from AROWOSEGBE ALICE MORADEKE","date":1740700800000,"balance":10000.0},{"type":"debit","amount":50.0,"narration":"Electronic Money Transfer Levy","date":1740700800000,"balance":9950.0},{"type":"credit","amount":20000.0,"narration":"Transfer from AROWOSEGBE ALICE MORADEKE","date":1741737600000,"balance":20000.0},{"type":"debit","amount":1500.0,"narration":"Transfer to THEOPHILUS OGAGAOGENE JONES","date":1741737600000,"balance":2700.0},{"type":"debit","amount":75.0,"narration":"Spend & Save Deposit","date":1741737600000,"balance":2625.0},{"type":"debit","amount":2500.0,"narration":"Transfer to Flory Mummy petrol station Odosida","date":1741737600000,"balance":125.0},{"type":"debit","amount":125.0,"narration":"Spend & Save Deposit","date":1741737600000,"balance":0.0},{"type":"debit","amount":6500.0,"narration":"Transfer to FELIX Iyanuoluwa ARIYO","date":1710028800000,"balance":20097.93},{"type":"debit","amount":325.0,"narration":"Spend & Save Deposit","date":1710028800000,"balance":19772.93},{"type":"credit","amount":5.0,"narration":"OWealth Interest Earned","date":1710115200000,"balance":14527.93},{"type":"debit","amount":2400.0,"narration":"Transfer to TOBILOBA PRAISE OYEKANMI","date":1710115200000,"balance":12127.93},{"type":"debit","amount":120.0,"narration":"Spend & Save Deposit","date":1710115200000,"balance":12007.93},{"type":"debit","amount":1000.0,"narration":"Transfer to OLUYIDE, JANET TOLANI","date":1710115200000,"balance":11007.93},{"type":"debit","amount":50.0,"narration":"Spend & Save Deposit","date":1710115200000,"balance":10957.93},{"type":"debit","amount":1100.0,"narration":"Transfer to Imisioluwa Oil Enterprise","date":1710115200000,"balance":9857.93},{"type":"debit","amount":55.0,"narration":"Spend & Save Deposit","date":1710115200000,"balance":9802.93},{"type":"credit","amount":3.37,"narration":"OWealth Interest Earned","date":1710201600000,"balance":9806.3},{"type":"debit","amount":400.0,"narration":"Airtime","date":1710201600000,"balance":9406.3},{"type":"debit","amount":25.0,"narration":"Spend & Save Deposit","date":1710201600000,"balance":9381.3},{"type":"debit","amount":9200.0,"narration":"Transfer to OLAPEJU ABIODUN","date":1710201600000,"balance":181.3},{"type":"credit","amount":294.69,"narration":"OWealth Deposit(AutoSave)","date":1710201600000,"balance":475.99},{"type":"credit","amount":0.16,"narration":"OWealth Interest Earned","date":1710288000000,"balance":476.15},{"type":"debit","amount":350.0,"narration":"Mobile Data","date":1710288000000,"balance":126.15},{"type":"debit","amount":17.5,"narration":"Spend & Save Deposit","date":1710288000000,"balance":108.65},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710374400000,"balance":108.74},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710460800000,"balance":108.83},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710547200000,"balance":108.92},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710633600000,"balance":109.01},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710720000000,"balance":109.1},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1710979200000,"balance":109.37},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1711065600000,"balance":109.46},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1711497600000,"balance":109.91},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1711584000000,"balance":4611.49},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1711670400000,"balance":4613.07},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1711756800000,"balance":4614.65},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1711843200000,"balance":4616.23},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1711929600000,"balance":4617.81},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1712016000000,"balance":4619.39},{"type":"credit","amount":1.58,"narration":"OWealth Interest Earned","date":1712188800000,"balance":4622.55},{"type":"debit","amount":62.5,"narration":"Spend & Save Deposit","date":1712620800000,"balance":1319.55},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1712707200000,"balance":269.64},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1712793600000,"balance":269.73},{"type":"credit","amount":10000.0,"narration":"OWealth Deposit(AutoSave)","date":1712880000000,"balance":10269.82},{"type":"credit","amount":3.53,"narration":"OWealth Interest Earned","date":1712966400000,"balance":10273.35},{"type":"credit","amount":45000.0,"narration":"OWealth Deposit(AutoSave)","date":1712966400000,"balance":55273.35},{"type":"credit","amount":19.04,"narration":"OWealth Interest Earned","date":1713052800000,"balance":55292.39},{"type":"debit","amount":1500.0,"narration":"Transfer to ADELEYE AKANDE SOYELE","date":1713052800000,"balance":41927.39},{"type":"debit","amount":2800.0,"narration":"Transfer to OLUWATOSIN DAMILARE AJEWOLE","date":1713052800000,"balance":36952.39},{"type":"debit","amount":140.0,"narration":"Spend & Save Deposit","date":1713052800000,"balance":36812.39},{"type":"credit","amount":12.68,"narration":"OWealth Interest Earned","date":1713139200000,"balance":36825.07},{"type":"credit","amount":10.88,"narration":"OWealth Interest Earned","date":1713225600000,"balance":31585.95},{"type":"debit","amount":5000.0,"narration":"Airtime","date":1713225600000,"balance":26585.95},{"type":"debit","amount":250.0,"narration":"Spend & Save Deposit","date":1713225600000,"balance":26335.95},{"type":"debit","amount":5.0,"narration":"Spend & Save Deposit","date":1713225600000,"balance":15520.95},{"type":"debit","amount":15000.0,"narration":"Transfer to AROWOSEGBE VICTOR IYANUOLUWA","date":1713225600000,"balance":520.95},{"type":"credit","amount":0.17,"narration":"OWealth Interest Earned","date":1713312000000,"balance":521.12},{"type":"credit","amount":0.17,"narration":"OWealth Interest Earned","date":1713398400000,"balance":521.29},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1713484800000,"balance":306.82},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1713657600000,"balance":307.0},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1713744000000,"balance":307.09},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1714003200000,"balance":307.36},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1714176000000,"balance":307.54},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1714435200000,"balance":6.31},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1714521600000,"balance":6.4},{"type":"credit","amount":10000.0,"narration":"OWealth Deposit(AutoSave)","date":1715126400000,"balance":10007.03},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1715385600000,"balance":149.19},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1715731200000,"balance":149.55},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1715904000000,"balance":149.73},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1717200000000,"balance":115.08},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1717286400000,"balance":115.17},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1718064000000,"balance":115.98},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1718409600000,"balance":116.34},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1718496000000,"balance":116.43},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1719446400000,"balance":117.42},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1719792000000,"balance":117.78},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720224000000,"balance":118.23},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720569600000,"balance":118.59},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720656000000,"balance":118.68},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720742400000,"balance":118.77},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720828800000,"balance":118.86},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1720915200000,"balance":118.95},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721001600000,"balance":119.04},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721088000000,"balance":119.13},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721174400000,"balance":119.22},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721260800000,"balance":119.31},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721347200000,"balance":119.4},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721433600000,"balance":119.49},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721520000000,"balance":119.58},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721606400000,"balance":119.67},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721692800000,"balance":119.76},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721779200000,"balance":119.85},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1721865600000,"balance":119.94},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1722038400000,"balance":120.12},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1722297600000,"balance":120.39},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1722384000000,"balance":120.48},{"type":"debit","amount":1.0,"narration":"Airtime","date":1729209600000,"balance":121.91},{"type":"credit","amount":15045.0,"narration":"OWealth Deposit","date":1729209600000,"balance":15166.91},{"type":"debit","amount":400.0,"narration":"Transfer to AYOKUNLE TIMOTHY OLAJIDE","date":1729296000000,"balance":14767.0},{"type":"debit","amount":20.0,"narration":"Spend & Save Deposit","date":1729296000000,"balance":14747.0},{"type":"debit","amount":10300.0,"narration":"Transfer to OGUNDIPE VENTURE","date":1729296000000,"balance":4447.0},{"type":"debit","amount":515.0,"narration":"Spend & Save Deposit","date":1729296000000,"balance":3932.0},{"type":"credit","amount":1.35,"narration":"OWealth Interest Earned","date":1729468800000,"balance":3934.7},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1729555200000,"balance":0.92},{"type":"credit","amount":4622.5,"narration":"OWealth Deposit(AutoSave)","date":1730332800000,"balance":4646.23},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned","date":1731283200000,"balance":138.82},{"type":"debit","amount":100.0,"narration":"Airtime","date":1731283200000,"balance":38.82},{"type":"debit","amount":5.0,"narration":"Spend & Save Deposit","date":1731283200000,"balance":33.82},{"type":"credit","amount":545.54,"narration":"OWealth Deposit(from Spend & Save)","date":1731283200000,"balance":579.36},{"type":"debit","amount":461.0,"narration":"Airtime","date":1731283200000,"balance":118.36},{"type":"debit","amount":25.0,"narration":"Spend & Save Deposit","date":1731283200000,"balance":93.36},{"type":"credit","amount":0.09,"narration":"OWealth Interest Earned

### Reviewing Profit/Loss Statement

In [91]:
transformed_opay_df.groupby('type')['amount'].sum()
credit = 1276721.75
debit = 1264022.21

diff = credit - debit
diff

12699.540000000037

Expected difference

In [94]:
credit - 1276757.21

-35.45999999996275

##### More work is to be done. 
Credit is correct. But Debit seems to be missing some values

`expected difference is = -35.46`